### ISSUE TITLE
Exception occurs while moving from the Google Map screen to the photo detail screen.

### ISSUE THREAD

**Issue by galaxy821** [CAU23-Capstone-Design/client#1]
When there is only one photo, click the photo on the calendar pop-up screen to move to the photo detail screen, then return to the Google Map screen and click the photo detail screen. The following error occurs.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lovestory.lovestory, PID: 16850
    java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
        at kotlin.collections.EmptyList.get(Collections.kt:36)
        at kotlin.collections.EmptyList.get(Collections.kt:24)
        at com.lovestory.lovestory.ui.screens.PhotoDetailScreenKt$ClickPhotoDetailScreenFromServer$5$3$1$1$2.invoke(PhotoDetailScreen.kt:629)
        ...
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
        ...
`

**Comment by galaxy821** [comment]
delete variable syncedPhoto and change load photo info logic
